config/routes.rb
Intervac::Application.routes.draw do
  # Custom error pages handled through the erros controller
  match '/404' => 'errors#not_found'
  match '/422' => 'errors#server_error'
  match '/500' => 'errors#server_error'

  # Namespaces and scopes to consolidate back office features
  namespace :management do
    get '/admin/dashboard', to: 'dashboards#admin'
    get '/agent/dashboard', to: 'dashboards#agent'
  end

  scope 'management' do
    # Agent management routes for both agents and admins
    resources :agents do
      get 'fetch_user', on: :collection
      member do
        post 'create_profile_image'
        delete 'destroy_profile_image'
        put 'add_agent_to_country', path: 'add-to-country'
        delete 'remove_agent_from_country', path: 'remove-from-country/:country_short'
        get 'remove_as_agent_confirm', path: 'remove-as-agent-confirm'
        get 'remove_as_agent', path: 'remove-as-agent'
      end
    end

    resources :accounts, module: 'accounts' do
      member do
        put 'set_nr_of_exchanges', path: 'set-nr-of-exchanges'
        put 'update_nr_of_allowed_listings', path: 'update-nr-of-allowed-listings'
        put 'set_joined_at', path: 'set_joined_at'
        put 'set_as_ambassador', path: 'set_as_ambassador'
        get 'confirm_termination', path: 'confirm/termination'
        get 'terminate'
      end
      get 'termination_confirmed', :on => :collection, :path => 'termination/confirmed'
    end

    resources :accounts, only: :none do
      get 'new_listing_as_agent' => 'listings', path: 'new/listing', as: 'new_listing'
      post 'create_listing_as_agent' => 'listings', path: 'create/listing', as: 'create_listing'

      resources :subscriptions, module: 'payment', only: :none do
        collection do
          get 'upgrade_account_as_agent', path: 'upgrade', as: 'upgrade'
          get 'renew_account_as_agent', path: 'renew', as: 'renew'
          post 'do_upgrade_or_renewal_as_agent', path: 'do-upgrade', as: 'do_upgrade'
          get 'account_upgraded_or_renewed_as_agent', path: 'upgraded', as: 'upgraded'
        end

        get 'full_details', on: :member, path: 'full-details', as: 'full_details'
      end
    end

    resources :base_listing, module: 'base', only: [:confirm_destroy, :destroy, :update_listing_number], as: 'management_listing', path: 'listings' do
      get 'confirm_destroy', path: 'confirm-destroy'
    end

    resources :listing_numbers, module: 'listings', only: [:edit, :update], as: 'management_listing_numbers', path: 'listing-numbers'
    resources :custom_city_and_country_headlines, module: 'listings', only: [:edit, :update], as: 'management_custom_city_and_country_headlines', path: 'customize-headline'

    match 'account/transfer/:account_id' => 'accounts/accounts#transfer_account', as: 'management_transfer', :via => :put
    match 'account/set-beta-access/:account_id/:access' => 'accounts/accounts#set_beta_access', as: 'set_beta_access', :via => :get

    resources :users, module: 'users', only: :none do
      member do
        get 'change_password_by_admin', path: 'change-password'
        put 'save_password_by_admin', path: 'save-password'
      end
    end

  end

  match '/translations/toggle' => 'admin/translations#toggle_translation', :via => :get, :as => 'toggle_translation'

  scope :module => "registration" do
    resources :price_plans, :path => 'price-plans' do
      get 'options', :on => :collection
      post 'promotion_code', :on => :collection, :path => 'promotion/code'
    end
  end

  match 'switch_user' => 'switch_user#set_current_user'
  match '/country-of-residence/(:country_short)' => 'registration/price_plans#country_of_residence', :via => [:get, :post], :as => 'country_of_residence'

  devise_scope :user do
    get "/logout" => "users/sessions#destroy", :path => 'service/logout'
    get "/login" => "users/sessions#new", :path => 'service/login'
    get "/resend_confirmation" => "users/registrations#resend_confirmation", :path => 'resend-confirmation'
    match '/signup/plan/:id/(:promotion_code)(.:format)' => 'users/registrations#new', :via => [:get, :post], :as => 'signup_plan'
    match '/signup/paid-plan/confirmation' => 'users/registrations#signup_confirmation_paid_plans', :via => :get, :as => 'paid_plan_confirmation'
    match '/signup/free-plan/confirmation' => 'users/registrations#signup_confirmation_free_plan', :via => :get, :as => 'free_plan_confirmation'
    match '/signup/paid-plan/cancel/:id' => 'users/registrations#cancel_signup', :via => :get, :as => 'cancel_signup'
    match '/signup/cancelled' => 'users/registrations#signup_cancelled', :via => :get, :as => 'signup_cancelled'
    match '/signup/skip-to-dashboard' => 'users/registrations#skip_to_dashboard', :via => :get, :as => 'skip_to_dashboard'
  end

  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions", :omniauth_callbacks => "users/omniauth_callbacks", :passwords => "users/passwords", :invitations => 'users/invitations'}

  match 'dashboard/overview' => 'dashboards#index', :via => :get, :as => 'member_dashboard'
  match 'dashboard/find-member-by-name' => 'dashboards#find_member_by_name', :via => :get, :as => 'find_member_by_name'
  match 'dashboard/find-member-by-number' => 'dashboards#find_member_by_number', :via => :get, :as => 'find_member_by_number'
  match 'guide/profile/address' => 'dashboards#profile_address', :via => :get, :as => 'guide_profile_address'
  match 'guide/profile/save/address' => 'dashboards#save_profile_address', :via => :post, :as => 'save_guide_profile_address'
  match '/dashboard/member/management' => 'dashboards#member_dashboard_for_management', via: :get, as: 'management_member_dashboard'
  match '/dashboard/information' => 'dashboards#information_page', via: :get, as: 'information_page'
  match '/dashboard/information/search' => 'dashboards#information_search', via: :get, as: 'information_search'

  scope :module => "users" do
    resource :user, :only => [:show, :edit_password, :save_password, :edit_email, :save_email] do
      member do
        get 'edit_password', :path => 'password/edit'
        put 'save_password', :path => 'password/save'
        get 'edit_primary_email', :path => 'email/edit/primary'
        put 'save_primary_email', :path => 'email/save/primary'
        get 'edit_secondary_email', :path => 'email/edit/secondary'
        delete 'delete_secondary_email', :path => 'email/delete/secondary'
        put 'save_secondary_email', :path => 'email/save/secondary'
        get 'edit_full_name', :path => 'full-name/edit'
        put 'save_full_name', :path => 'full-name/save'
        get 'connect_facebook', :path => 'connect-facebook'
      end
    end

    resource :facebook_graph, :path => 'facebook' do
      member do
        get 'connect'
        get 'link_account'
        get 'user_denied'
      end
    end
  end

  match '/accounts-listings/build' => 'accounts_listings#build', :via => :get, :as => 'build_accounts_listings'

  match '/missing-photos' => 'listings/missing_photos#index',  :via => :get, :as => 'missing_photos'
  match '/missing-photos/update' => 'listings/missing_photos#update',  :via => :post, :as => 'missing_photos_update'

  # Searching
  match '/search' => 'searches#index', :via => :get, :as => 'searches_index'
  match '/search/search' => 'searches#search', :via => :get, :as => 'searches_search'
  match '/search/map' => 'searches#map', :via => :get, :as => 'searches_map'
  match '/search/map-search' => 'searches#map_search', :via => :get, :as => 'searches_map_search'
  match '/search/listing-info/:listing_number' => 'searches#listing_info', :via => :get, :as => 'listing_info'
  match '/search/mapview-coords' => 'searches#mapview_coords', :via => :get
  match '/search/go-to-listing' => 'searches#go_to_listing', :via => :get, :as => 'searches_go_to_listing'
  match '/search/:id/find' => 'searches#do_saved_search', :via => :get, :as => 'do_saved_search'
  match '/search/save' => 'searches#save_search', :via => :post, :as => 'save_search'
  match '/search/delete' => 'searches#delete_saved_search', :via => :post, :as => 'delete_saved_search'

  # Listing routes
  resources :listings do
    collection do
      post 'find', :path => 'find'
      post 'get_listings', :path => 'get/listings'
    end

    member do
      get 'overview'
      get 'preview', as: 'preview'
      get 'enable'
      get 'disable'
      get 'exchange_settings', path: 'exchange-settings'
    end

    match '/set-availability/:availability' => "listings#set_availability_for_exchange", :via => :get, :as => 'set_availability'
    match '/set-availability-with-hotlist/:availability' => "listings#set_availability_with_hotlist", :via => :get, :as => 'set_availability_with_hotlist'

    # All listings resources should be moved and mapped in to this scope
    scope :module => "listings" do
      resource :presentations, only: [:show, :edit, :update] do
        get 'cancel', :on => :collection
      end

      resource :main_photos, only: [:show, :edit, :update] do
        post 'upload'
        get 'edit_caption'
        put 'update_caption'
        get 'cancel_caption'
      end

      resource :headlines, only: [:edit, :update] do
        get 'cancel'
      end
    end

    scope :module => "listing" do
      resource :location, :only => [:edit, :update] do
        get 'cancel', :on => :collection
      end
      match '/location/update-visibility/:status' => "locations#update_visibility", :via => :get, :as => 'update_visibility'

      resource :description, :only => [:edit, :update, :cancel] do
        get 'cancel', :on => :collection
      end

      resource :rule, :only => [:edit, :update, :cancel] do
        get 'cancel', :on => :collection
      end

      resource :property_setting, path: "property-settings", :only => [:edit, :update, :cancel] do
        get 'cancel', :on => :collection
      end

app/controllers/automated_messages_controller.rb
# encoding: UTF-8
class AutomatedMessagesController < ApplicationController
  filter_access_to :all
  layout 'management'

  ##
  # Shows all the automated messages for a single country
  def for_country
    @country = Country.find(params[:country_id])
    @messages = AutomatedMessage.where(:countries.in => [@country.short]).order_by(:name, :asc)

    respond_to do |format|
      format.html
    end
  end

  ##
  # Edits a single message displayed based on a country
  def edit_for_country
    @automated_message = AutomatedMessage.find(params[:id])
    @message_types = AutomatedMessage.get_message_kinds()
    @country = Country.find(params[:country_id])
    @countries = Country.only(:msgid, :short).collect {|c| [ t(c['msgid']), c['short'] ] }.sort
    @placeholders = AutomatedMessage.get_placeholders_for_message(@automated_message.kind)

    respond_to do |format|
      format.html
    end
  end

  def update_for_country
    @country = Country.find(params[:country_id])
    @automated_message = AutomatedMessage.find(params[:id])
    @automated_message.update_message(params[:automated_message], current_user.id)

    respond_to do |format|
      if @automated_message.save
        format.html {redirect_to(for_country_automated_messages_path(@country))}
      else
        @placeholders = AutomatedMessage.get_placeholders_for_message(params[:automated_message][:kind])
        @message_types = AutomatedMessage.get_message_kinds()
        @countries = Country.only(:msgid, :short).collect {|c| [ t(c['msgid']), c['short'] ] }.sort
        format.html {render(action: 'edit_for_country')}
      end
    end
  end

  def destroy_for_country
    @country = Country.find(params[:country_id])
    @automated_message = AutomatedMessage.find(params[:id])
    @automated_message.delete

    respond_to do |format|
      format.html {redirect_to(for_country_automated_messages_path(@country))}
    end
  end

  def index
    @messages = AutomatedMessage.where(:countries.in => current_user.agent_profile.get_assigned_countries_short_codes).order_by(:name, :asc)

    respond_to do |format|
      format.html
    end
  end

  def new
    @automated_message = AutomatedMessage.new
    @message_types = AutomatedMessage.get_message_kinds()
    @countries = current_user.agent_profile.agent_for.collect {|c| [ t(c['msgid']), c['short'] ] }.sort
    @placeholders = 'Choose a message kind'

    respond_to do |format|
      format.html
    end
  end

  ##
  # Lists all the default messages
  def show_default
    @automated_messages = AutomatedMessage.where(:countries.in => ['default'])
    respond_to do |format|
      format.html
    end
  end

  ##
  # Edit a single default message
  def edit_default
    @automated_message = AutomatedMessage.find(params[:id])
    @message_types = AutomatedMessage.get_message_kinds()
    @placeholders = AutomatedMessage.get_placeholders_for_message(@automated_message.kind)

    respond_to do |format|
      format.html
    end
  end

  def update_default
    @automated_message = AutomatedMessage.find(params[:id])
    @automated_message.update_message(params[:automated_message], current_user.id)

    respond_to do |format|
      if @automated_message.save
        format.html {redirect_to(action: 'show_default')}
      else
        @placeholders = AutomatedMessage.get_placeholders_for_message(params[:automated_message][:kind])
        @message_types = AutomatedMessage.get_message_kinds()
        format.html {render(action: 'edit_default')}
      end
    end
  end

  def create
    @automated_message = AutomatedMessage.new(
      name: AutomatedMessage.get_message_name(params[:automated_message][:kind]),
      kind: params[:automated_message][:kind],
      subject: params[:automated_message][:subject],
      message: params[:automated_message][:message],
      days: params[:automated_message][:days],
      countries: params[:automated_message][:countries],
      created_by: current_user.id,
      send_copy_to_agent: params[:automated_message][:send_copy_to_agent]
    )

    respond_to do |format|
      if @automated_message.save
        format.html {redirect_to(automated_messages_path)}
      else
        @message_types = AutomatedMessage.get_message_kinds()
        @countries = current_user.agent_profile.agent_for.collect {|c| [ t(c['msgid']), c['short'] ] }.sort
        @placeholders = AutomatedMessage.get_placeholders_for_message(params[:automated_message][:kind])
        if @automated_message.countries.nil?
          @automated_message.countries = []
        end
        format.html { render(action: 'new') }
      end
    end
  end

  def edit
    @automated_message = AutomatedMessage.find(params[:id])
    @message_types = AutomatedMessage.get_message_kinds()
    @countries = current_user.agent_profile.agent_for.collect {|c| [ t(c['msgid']), c['short'] ] }.sort
    @placeholders = AutomatedMessage.get_placeholders_for_message(@automated_message.kind)

    respond_to do |format|
      format.html
    end
  end

  def update
    @automated_message = AutomatedMessage.find(params[:id])
    @automated_message.update_message(params[:automated_message], current_user.id)

    respond_to do |format|
      if @automated_message.save
        format.html {redirect_to(action: 'index')}
      else
        @placeholders = AutomatedMessage.get_placeholders_for_message(params[:automated_message][:kind])
        @message_types = AutomatedMessage.get_message_kinds()
        @countries = current_user.agent_profile.agent_for.collect {|c| [ t(c['msgid']), c['short'] ] }.sort
        format.html {render(action: 'edit')}
      end
    end
  end

  def destroy
    @automated_message = AutomatedMessage.find(params[:id])
    @automated_message.delete

    respond_to do |format|
      format.html { redirect_to(action: 'index') }
    end
  end

  ##
  # Used by the drop-down selector to update the available placeholders for the specific message type
  def update_meta_data
    message = params[:selected]
    @placeholders = AutomatedMessage.get_placeholders_for_message(message)
    @days = AutomatedMessage.get_days_for_message(message)

    respond_to do |format|
      format.js
    end
  end

  def preview
    @placeholders = {}
    @placeholders[:MEMBER_NAME] = "INTERVAC USER (Decprecated use FAMILY_NAME instead)"
    @placeholders[:FAMILY_NAME] = "INTERVAC USER"
    @placeholders[:FAMILY_ID] = 123456
    @placeholders[:COUNTRY] = "SE"
    @placeholders[:LOGIN] = "user@domain.com"
    @placeholders[:EXPIRE_DAYS] = "5"
    @placeholders[:DEACTIVATION_DATE] = Date.today.strftime("%F")

    @placeholders[:SUBSCRIPTION_LINK] = upgrade_subscriptions_url
    @placeholders[:FEEDBACK_LINK] = ActionController::Base.helpers.link_to('Home exchange feedback', exchange_feedbacks_url)
    @placeholders[:NUMBER] = '14'
    @placeholders[:LAST_LOGIN_IN_DAYS] = ((Time.now.utc - current_user.account.accessed_at.utc).to_i / 3600 / 24)

    @agent_placeholders = {}
    @agent_placeholders[:MY_NAME] = "AGENT NAME"
    @agent_placeholders[:MY_EMAIL] = "AGENT E-MAIL"
    @agent_placeholders[:MY_PHONE] = "AGENT PHONE"
    @agent_placeholders[:MY_FAX] = "AGENT FAX"
    @agent_placeholders[:MY_URL] = "AGENT WEBSITE"
    @agent_placeholders[:MY_COUNTRY] = "AGENT COUNTRY"
    @agent_placeholders[:LISTING_ID] = "LISTING NUMBER"

    @placeholders.merge!(@agent_placeholders)

    @preview_message = {
      subject: params[:automated_message][:subject],
      body: params[:automated_message][:message]
    }

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/automated_messages_helper.rb
module AutomatedMessagesHelper
end

app/views/automated_messages/_automated_messages_form.html.erb
<%= form_for(@automated_message, html: {id: 'automated-message-form'}) do |f| %>
    <%= render(partial: 'automated_messages_form_fields', locals: {f: f}) %>
<%- end -%>

app/views/automated_messages/_automated_messages_form_fields.html.erb
  <% if @automated_message.errors.any? %>
    <section id="error-explanation" class="alert alert-danger">
      <h1 class="alert-heading"><%= pluralize(@automated_message.errors.count, "error") %> from being saved</h1>
      <ul class="error-explanation">
      <% @automated_message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </section>
  <% end %>

  <fieldset>
    <%= f.label(:kind, 'Kind of message', for: 'message-kind') %>
    <%= f.select(:kind, @message_types, { :prompt => 'Select message kind' }, {id: 'message-kind', class: 'form-control'}) %>

    <div id="message-section">
      <%= f.label(:subject, 'Message subject - Only used on the mail subject header, not in the actual message body', for: 'message-subject') %>
      <%= f.text_field(:subject, class: 'span12', id: 'message-subject') %>

      <%= f.label(:message, 'Message body content - Markdown is supported', for: 'message-body') %>
      <%= f.text_area(:message, rows: 16, class: 'span12', id: 'message-body') %>

      <button type="button" class="btn" id="btn-preview">Preview message</button>
    </div>

    <h2 class="section-header">Placeholders available for this message. Additional placeholders have to be requested by the board.</h2>
    <p id="placeholders" class="alert alert-info"><%= @placeholders %></p>
  </fieldset>

  <fieldset>
    <h2 class="section-header">Settings</h2>
    <%= f.label(:days, 'Number of days before or after the event the message should be sent', for: 'message-days') %>
    <%= f.text_field(:days, maxlength: 3, class: 'span1', id: 'message-days') %>
  </fieldset>

  <fieldset>
    <h2 class="section-header">Should be used for the following countries</h2>
    <p><button id="btn-select-all" class="btn btn-small" type="button">Select all countries</button> <button id="btn-deselect-all" class="btn btn-small" type="button">Deselect all countries</button></p>
    <% @countries.each do |country| %>
        <%= f.label(:countries, for: "country-#{country[1]}", class: 'checkbox') do %>
            <%= check_box_tag('automated_message[countries][]', country[1], @automated_message.countries.include?(country[1]), id: "country-#{country[1]}", class: 'country-check-box') %>
            <%= country[0] %>
        <% end %>
    <% end %>
  </fieldset>

  <fieldset>
    <h2 class="section-header">Receive a email copy of the message</h2>
    <%= f.label(:send_copy_to_agent, for: 'send-copy-true', class: 'radio') do %>
      <%= f.radio_button(:send_copy_to_agent, true, id: 'send-copy-true') %>
      yes
    <% end %>

    <%= f.label(:send_copy_to_agent, for: 'send-copy-false', class: 'radio') do %>
      <%= f.radio_button(:send_copy_to_agent, false, id: 'send-copy-false') %>
      no
    <% end %>
  </fieldset>

  <fieldset class="form-actions">
    <%= f.submit('Save', class: 'btn btn-primary') %>
    <%- if agent_session? -%>
      <%= link_to('Cancel', automated_messages_path) %>
    <%- else -%>
      <%= link_to('Cancel', for_country_automated_messages_path(@country)) %>
    <%- end -%>
  </fieldset>

  <script type="text/javascript">
      automated_messages_select_deselect();
      automated_messages_kind();
      automated_messages_preview_actions();
  </script>

app/views/automated_messages/_automated_messages_form_for_country.html.erb
<%= form_for(@automated_message, url: update_for_country_automated_message_path(@automated_message, @country), html: {id: 'automated-message-form'}) do |f| %>
  <%= render(partial: 'automated_messages_form_fields', locals: {f: f}) %>
<%- end -%>

app/views/automated_messages/_default_message.html.erb
<section id="default-message">
    <article class="alert alert-info">
        <h1 class="page-header"><%= default_message[:subject] %></h1>
        <%= markdown(default_message[:message]) %>
    </article>
</section>

app/views/automated_messages/_preview.html.erb
<section id="message-preview" class="message-preview">
    <article>
        <h1 class="page-header"><%= preview_message[:subject] %></h1>
        <%= markdown(preview_message[:body] % @placeholders) %>
    </article>
    <%= link_to('Close preview', '#', class: 'btn', id: 'btn-close-preview') %>
</section>

app/views/automated_messages/edit.html.erb
<% body_id 'payment' %>
<div class="row-fluid">
  <div class="span12">
    <nav id="section-nav" role="secondary">
      <%= render(partial: '/payment/payment_settings_menu') %>
    </nav>
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
    <div class="plate">
      <div class="plate-content">
        <h1 class="plate-header"><%= @automated_message.name %> - Automated messages</h1>
        <div class="mb20">
          <span>Return to <%= link_to('automated messages', automated_messages_path) %></span>
        </div>
        <%= render(partial: 'automated_messages_form') %>
      </div>
    </div>
  </div>
</div>

app/views/automated_messages/edit_default.html.erb
<% body_id 'translations' %>

<%= render(locals: {header: "Editing default message #{@automated_message.name}"}, layout: '/layouts/modules/single_page_plate') do %>
    <%= form_for(@automated_message, url: update_default_automated_message_path, html: {id: 'automated-message-form'}) do |f| %>
        <% if @automated_message.errors.any? %>
            <section id="error-explanation" class="alert alert-danger">
                <h1 class="alert-heading"><%= pluralize(@automated_message.errors.count, "error") %> from being saved</h1>
                <ul class="error-explanation">
                    <% @automated_message.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </section>
        <% end %>

        <fieldset>
            <%= f.label(:kind, 'Kind of message', for: 'message-kind') %>
            <%= f.select(:kind, @message_types, { :prompt => 'Select message kind' }, {id: 'message-kind', class: 'form-control'}) %>

            <div id="message-section" class="mb20">
                <%= f.label(:subject, 'Message subject - Only used on the mail subject header, not in the actual message body', for: 'message-subject') %>
                <%= f.text_field(:subject, class: 'span12', id: 'message-subject') %>

                <%= f.label(:message, 'Message body content - Markdown is supported', for: 'message-body') %>
                <%= f.text_area(:message, rows: 16, class: 'span12', id: 'message-body') %>

                <button type="button" class="btn" id="btn-preview">Preview message</button>
            </div>

            <h2 class="plate-section-header">Placeholders available for this message. Additional placeholders have to be requested by the board.</h2>
            <p id="placeholders" class="alert alert-info"><%= @placeholders %></p>
        </fieldset>

        <fieldset>
            <h2 class="plate-section-header">Send out settings</h2>
            <%= f.label(:days, 'Number of days before or after the event the message should be sent', for: 'message-days') %>
            <%= f.text_field(:days, maxlength: 3, class: 'span1', id: 'message-days') %>
        </fieldset>

        <fieldset>
            <h2 class="plate-section-header">Should agents receive a email copy of the message?</h2>
            <%= f.label(:send_copy_to_agent, for: 'send-copy-true', class: 'radio') do %>
                <%= f.radio_button(:send_copy_to_agent, true, id: 'send-copy-true') %>
                yes
            <% end %>

            <%= f.label(:send_copy_to_agent, for: 'send-copy-false', class: 'radio') do %>
                <%= f.radio_button(:send_copy_to_agent, false, id: 'send-copy-false') %>
                no
            <% end %>
        </fieldset>

        <fieldset>
            <%= f.submit('Save', class: 'btn btn-primary') %>
            <%= link_to('Cancel', show_default_automated_messages_path, class: 'btn btn-link') %>
            <%= hidden_field_tag('automated_message[countries][]', 'default') %>
        </fieldset>
    <%- end -%>
<% end %>

<script type="text/javascript">
    automated_messages_kind();
    automated_messages_preview_actions();
</script>

app/views/automated_messages/edit_for_country.html.erb
<% body_id 'countries' %>
<div class="row-fluid">
  <div class="span3">
    <%= render(partial: 'countries/management_menu', locals: {country: @country}) %>
  </div>
  <div class="span9">
    <div class="plate">
      <div class="plate-content">
        <h1 class="plate-header"><%= @automated_message.name %></h1>
        <%= render(partial: 'automated_messages_form_for_country') %>
      </div>
    </div>
  </div>
</div>

app/views/automated_messages/index.html.erb
<% body_id 'payment' %>
<div class="row-fluid">
  <div class="span12">
    <nav id="section-nav" role="secondary">
      <%= render(partial: '/payment/payment_settings_menu') %>
    </nav>
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
    <div class="plate">
      <div class="plate-content">
        <h1 class="plate-header">Automated messages</h1>
        <p>You have access to the following automated messages</p>

        <table class="table">
          <thead>
            <tr>
              <th>Message kind</th>
              <th>Used by countries</th>
              <th>Agent gets copy</th>
              <th>Days before or after event</th>
            </tr>
          </thead>
          <tbody>
          <% @messages.each do |message| %>
          <tr>
            <td><%= link_to(message.name, edit_automated_message_path(message)) %></td>
            <td>
              <% message.countries.each_index do |k| %>
                <%= message.countries[k] %>
              <% end %>
            </td>
            <td>
              <% if message.send_copy_to_agent %>
                Yes
              <% else %>
                No
              <% end %>
            </td>
            <td>
              <% if message.days == 0 %>
                Instant
              <% else %>
                <%= message.days %> days
              <% end %>
            </td>
            <td>
              <%= link_to('Delete', automated_message_path(message), method: :delete, confirm: 'Are you sure you want to delete this automated message?') %>
            </td>
          </tr>
          <% end %>
          </tbody>
        </table>

        <%= link_to('New message', new_automated_message_path, class: 'btn') %>

      </div>
    </div>
  </div>
</div>

app/views/automated_messages/preview.js.erb
$('#message-section').hide();
$('#message-section').after("<%= escape_javascript(render(partial: 'preview', locals: {preview_message: @preview_message})) %>");

app/views/automated_messages/show_default.html.erb
<% body_id 'translations' %>

<%= link_to('Translations overview', admin_translations_path, class: 'btn mb20') %>

<%= render(locals: {header: 'Default automated messages'}, layout: '/layouts/modules/single_page_plate') do %>
    <table class="table">
        <thead>
            <tr>
                <th>Message kind</th>
                <th>Used by countries</th>
                <th>Agent gets copy</th>
                <th>Days before or after event</th>
            </tr>
        </thead>
        <tbody>
            <% @automated_messages.each do |message| %>
                <tr>
                    <td><%= link_to(message.name, edit_default_automated_message_path(message)) %></td>
                    <td>
                        <% message.countries.each_index do |k| %>
                            <%= message.countries[k] %>
                        <% end %>
                    </td>
                    <td>
                        <% if message.send_copy_to_agent %>
                            Yes
                        <% else %>
                            No
                        <% end %>
                    </td>
                    <td>
                        <% if message.days == 0 %>
                            Instant
                        <% else %>
                            <%= message.days %> days
                        <% end %>
                    </td>
                    <td>
                        <%= link_to('Delete', automated_message_path(message), method: :delete, confirm: 'Are you sure you want to delete this automated message?') %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>